[package]
name = "bintex_derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
deku = "0.16.0"
syn = "2.0"
darling = "0.20.0"
proc-macro2 = "1.0"
quote = "1.0"
