on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  # build, test all supported targets
  build-test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-musl
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.targets }}
      - run: cargo build --locked --workspace --target ${{ matrix.targets }}

  # fmt and clippy
  fmt-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings
