on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  # build, test all supported targets
  build-test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-musl
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.targets }}
      - run: cargo build --locked --workspace --target ${{ matrix.targets }}

  # fmt and clippy
  fmt-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings
